FROM golang:1.22.1 as base

FROM base as documentation
WORKDIR /app

COPY . .
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init -g ./main/main.go -o ./main/docs

FROM base as builder

WORKDIR /app

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o server ./main

FROM scratch as production

WORKDIR /app

COPY --from=builder /app/server .
ENV GIN_MODE=release

EXPOSE 3000

CMD ["./server"]